# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Run plgd/hub tests with cloud_server

on:
  push:

env:
  TAG_NAME: cloud-server-debug:debug
  CONTAINER_NAME: cloud-server
  TEST_CLOUD_SERVER_IMAGE: ghcr.io/plgd-dev/hub/test-cloud-server:latest

jobs:
  plgd-hub-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
     
      - name: Build cloud server docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: false
          file: ./docker/apps/Dockerfile.cloud-server-debug
          tags: ${{ env.TAG_NAME }}
      
      - name: Pull plgd hub tests image
        run: docker pull ${{ env.TEST_CLOUD_SERVER_IMAGE }}

      - name: Run cloud server container
        run: docker run --privileged -d --network=host -v `pwd`/data:/tmp --name ${{ env.CONTAINER_NAME }} ${{ env.TAG_NAME }} devsim-`hostname`

      - name: Run plgd hub tests image
        run: docker run --rm --network=host ${{ env.TEST_CLOUD_SERVER_IMAGE }}

      - name: Collect cloud server logs when the test fails
        if: ${{ failure() }}
        uses: actions/upload-artifact@v2
        with:
          name: cloud-server-log
          path: "./data/0.log"

      - name: Remove cloud server container
        run: docker rm -f ${{ env.CONTAINER_NAME }}
      

